name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ master ]  # 监听 master 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # 如果主题是子模块，需启用
          token: ${{ secrets.GITHUB_TOKEN }}  # 显式传递权限

      # 2. 安装 Hugo（Extended 版本）
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # 必须启用 Extended 版本

      # 3. 构建静态文件
      - name: Build
        run: hugo --minify --baseURL "https://null186.github.io/myblog/"  # 替换为你的地址

      # 4. 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo 默认输出目录
          force_orphan: true

